<a href="https://colab.research.google.com/github/SimplyMias/maths-AI-ML/blob/main/NumpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating Array**

In [1]:
import numpy as np # importing numpy

np.zeros = it is a function which creates an array  of any number of zeros

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

To make 2D array (a matrix) provide a tuple with num of rows and num of columns
Example 3X4 matrix

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**Some Vocabulary**

In Numpy each Dimension is called axis
the number of axes is called rank

Example the above 3X4 matrix is an array of rank 2

the first axis has length 3 and the second axis has  length 4

An array's list of axes is shape of the array

Eample, above matrix's shape is (3,4). The rank is equal to the shape length

The size of an array is the total number of elements, which is the product of all axis lengths (e.g. 3*4=12)

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.shape

(3, 4)

In [6]:
a.ndim  # same as len(a.shape)

2

In [8]:
a.size

12