<a href="https://colab.research.google.com/github/SimplyMias/maths-AI-ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning Numpy

Creating Arrays

In [1]:
import numpy as np


np.zeros
The zero function creates an array containing any number of zeros

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

to create a 2D array (i.e, matrix) we need to provide a tuple with desired num of rows and columns. For Example, here's 3x4 matrix

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

SOME Vocabulary

In numpy each dimension is called an axis

The number of axes is called the rank.

For example the above 3x4 matrix is an array of rank 2 (it is 2-Dimensional)

the first axes has length 3 and second has length 4

An array's list of axis lengths is called the shape of the array

For example the above matrix's shape is (3,4)

The Rank is equal to the Shape's length

The size of an array is the total number of elements, which is the product of all axis lengths (e.g. 3*4=12)

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.shape

(3, 4)

In [6]:
a.ndim  # equal to len(a.shape)

2

In [7]:
a.size

12

N-Dimensional Arrays


creating array of arrbitrary rank

For Example here is a 3D array (rank = 3) with shape (2,3,4)

In [8]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Array Type

NumPy arrays have the type ndarray s:

In [9]:
type(np.zeros((3,4)))

numpy.ndarray

np.ones

Many other NumPy functions create ndarrays.

Here's a 3x4 matrix full of ones:

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.full

Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of π.

In [11]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

**np.empty**

An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

In [12]:
np.empty((2,3))

array([[3.42037443e-315, 0.00000000e+000, 2.43722670e-152],
       [1.94208380e+227, 9.08367203e+223, 6.01347002e-154]])

**np.array**

Of course, you can initialize an ndarray using a regular python array. Just call the array function:

In [13]:
np.array([[1,2,3,4],[10,20,30,40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

**np.arange**

You can create an ndarray using NumPy's arange function, which is similar to python's built-in range function:

In [14]:
np.arange(1,5)

array([1, 2, 3, 4])

it also works with floats:

In [15]:
np.arange(1.0,5.0)

array([1., 2., 3., 4.])

ofc you can provide a step parameter

In [16]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

However, when dealing with floats, the exact number of elements in the array is not always predictable For Example, consider this:

In [18]:
print(np.arange(0,5/3,1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0,5/3,0.333333333))
print(np.arange(0, 5/3, 0.333333334))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


**np.linspace**

For this reason, it is generally preferable to use the linspace function instead of arange when working with floats. The linspace function returns an array containing a specific number of points evenly distributed between two values (note that the maximum value is included, contrary to arange):

In [19]:
print(np.linspace(0, 5/3, 6))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
